name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: GitHub Pages 
      uses: cmgriffing/scully-gh-pages-action@v9
      with:
          deploy-branch: gh-pages
          access-token: ${{ secrets.ACCESS_TOKEN }}
          build-args: --prod
          scully-args: --scanRoutes --prod
